- hosts: ali
  user: root
  tasks:
      - name: debug
        debug:
          msg: "inventory_hostname {{ inventory_hostname }}"

      - name: copy thumbs
        copy:
          src: ~/WebstormProjects/laoshijia/public/images/thumbs
          dest: /root/projects/laoshijia/public/images
          owner: root
          group: root
#          mode: 0777

      - name: copy fulls
        copy:
          src: ~/WebstormProjects/laoshijia/public/images/fulls
          dest: /root/projects/laoshijia/public/images
          owner: root
          group: root
#          mode: 0777